In [1]:
import pandas as pd 

taiwan_charger = pd.read_csv("data\chargers_taiwan.csv")
taiwan_charger

<>:3: SyntaxWarning: invalid escape sequence '\c'
<>:3: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Administrator\AppData\Local\Temp\1\ipykernel_5568\3418978161.py:3: SyntaxWarning: invalid escape sequence '\c'
  taiwan_charger = pd.read_csv("data\chargers_taiwan.csv")

,access,addr:city,addr:country,addr:district,addr:floor,addr:full,addr:housenumber,addr:place,addr:postcode,addr:province,...,socket:type1,socket:type1:output,socket:type2_combo,socket:type2_combo:output,truck,voltage,website,wheelchair,longitude,latitude
0,NaN,臺南市,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,120.211556,22.982847
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.447906,25.064245
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.780317,24.274975
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.539717,24.085883
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.452972,25.044579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.534403,23.894819
277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.534377,23.894909
278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.218015,22.996648
279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.696151,25.155886
280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.410959,25.021169

In [2]:
taiwan_charger.info()

<class 'pandas.DataFrame'>
RangeIndex: 281 entries, 0 to 280
Data columns (total 67 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   access                             7 non-null      str
 1   addr:city                          57 non-null     str
 2   addr:country                       56 non-null     str
 3   addr:district                      56 non-null     str
 4   addr:floor                         1 non-null      float64
 5   addr:full                          1 non-null      str
 6   addr:housenumber                   56 non-null     str
 7   addr:place                         2 non-null      str
 8   addr:postcode                      17 non-null     float64
 9   addr:province                      20 non-null     str
 10  addr:street                        56 non-null     str
 11  amenity                            281 non-null    str
 12  bicycle                            8 non-null      str
 13  branch                             73 non-null     str
 14  brand                              153 non-null    str
 15  brand:en                           1 non-null      str
 16  brand:wikidata                     132 non-null    str
 17  brand:wikipedia                    14 non-null     str
 18  capacity                           35 non-null     str
 19  capacity:motorcar                  3 non-null      float64
 20  charging                           4 non-null      str
 21  charging_station:battery_swapping  1 non-null      str
 22  construction                       1 non-null      str
 23  covered                            12 non-null     str
 24  description                        15 non-null     str
 25  fee                                28 non-null     str
 26  fuel:octane_92                     1 non-null      str
 27  fuel:octane_95                     1 non-null      str
 28  fuel:octane_98                     1 non-null      str
 29  layer                              1 non-null      float64
 30  level                              10 non-null     float64
 31  mobile_phones                      1 non-null      str
 32  moped                              1 non-null      str
 33  motorcar                           12 non-null     str
 34  motorcycle                         3 non-null      str
 35  name                               219 non-null    str
 36  name:en                            13 non-null     str
 37  name:ja                            1 non-null      str
 38  name:zh                            16 non-null     str
 39  netbook                            1 non-null      str
 40  network                            7 non-null      str
 41  note                               2 non-null      str
 42  opening_hours                      8 non-null      str
 43  operator                           214 non-null    str
 44  operator:wikidata                  132 non-null    str
 45  operator:wikipedia                 13 non-null     str
 46  parking:fee                        1 non-null      str
 47  payment:app                        10 non-null     str
 48  phone                              1 non-null      float64
 49  postal_code                        6 non-null      float64
 50  ref                                2 non-null      str
 51  scooter                            10 non-null     str
 52  short_name                         4 non-null      str
 53  socket                             1 non-null      str
 54  socket:j1772                       2 non-null      float64
 55  socket:tesla_supercharger          3 non-null      float64
 56  socket:tesla_supercharger:output   1 non-null      float64
 57  socket:type1                       1 non-null      float64
 58  socket:type1:output                1 non-null      float64
 59  socket:type2_combo                 1 non-null      float64
 60  socket:type2_combo:output          1 non-null      float64
 61  truck                              3 non-null      str
 62  voltage                            1 non-null      float64
 63  website                            7 non-null      str
 64  wheelchair                         2 non-null      str
 65  longitude                          281 non-null    float64
 66  latitude                           281 non-null    float64
dtypes: float64(17), str(50)
memory usage: 147.2 KB

In [29]:
taiwan_charger_cleaned = taiwan_charger[[
    'name', "longitude", "latitude"
    ]]
taiwan_charger_cleaned

                    name   longitude   latitude
0    Gogoro 換電站 台亞大同路加油站  120.211556  22.982847
1                    NaN  121.447906  25.064245
2                    NaN  120.780317  24.274975
3                    充電室  120.539717  24.085883
4                    NaN  121.452972  25.044579
..                   ...         ...        ...
276           多容館充電樁（慢充）  121.534403  23.894819
277           多容館充電樁（快充）  121.534377  23.894909
278                  NaN  120.218015  22.996648
279         Gogoro 電池交換站  121.696151  25.155886
280                  NaN  121.410959  25.021169

[281 rows x 3 columns]

In [30]:
taiwan_charger_cleaned['name'].value_counts()

name
Gogoro 電池交換站    138
GoStation         4
Gogoro換電站         4
gogoro換電站         2
Gogoro            2
               ...
理工三館充電樁（慢充）       1
東華會館充電樁（快充）       1
東華會館充電樁（慢充）       1
多容館充電樁（慢充）        1
多容館充電樁（快充）        1
Name: count, Length: 72, dtype: int64

In [31]:
taiwan_charger_cleaned.isna().sum()
# Wallahi

name         62
longitude     0
latitude      0
dtype: int64

In [33]:
from sklearn.impute import SimpleImputer

imp_name = SimpleImputer(strategy='constant', fill_value="Unnamed")
taiwan_charger_cleaned_2 = imp_name.fit_transform(taiwan_charger_cleaned)
taiwan_charger_cleaned_2

array([['Gogoro 換電站 台亞大同路加油站', 120.2115564, 22.9828468],
       ['Unnamed', 121.4479064, 25.0642445],
       ['Unnamed', 120.7803173, 24.2749748],
       ['充電室', 120.5397166, 24.0858833],
       ['Unnamed', 121.4529721, 25.0445786],
       ['Unnamed', 121.5370166, 24.960521],
       ['BES電池交換站', 121.4653747, 25.0167771],
       ['電動車充電站', 121.1923304, 24.8003452],
       ['板橋後站', 121.4586405, 25.0073178],
       ['BES電池交換站 有利站', 121.4203508, 24.9811464],
       ['BES電池交換站 板橋體育館站', 121.4563526, 25.0130345],
       ['BES電池交換站 和平公園站', 121.4643381, 24.9975666],
       ['Gogoro GoStation 中油山隆樹林站', 121.4202873, 24.9819775],
       ['Unnamed', 120.6752218, 24.1209534],
       ['Go Station 換電站 - 中油北基基金站', 121.6498532, 25.2093658],
       ['Go Station 換電站 - 中油石門加油站', 121.5614161, 25.2912061],
       ['Go Station 換電站 - 大嘉好加油站', 121.4777053, 25.2598491],
       ['Go Station 換電站 - 中油淡海新市鎮站', 121.446183, 25.1918801],
       ['Go Station 換電站 - 台亞承德路站', 121.5039192, 25.116414],
       ['Go Station 換電站 - 中油陽明山站', 121.5457734, 25.1353594],
       ['Go Station 換電站 - 中油福林站', 121.5271774, 25.0924569],
       ['Go Station 換電站 - 禾悅生活士林店', 121.5222022, 25.0884212],
       ['Go Station 換電站', 121.5257407, 25.0873241],
       ['Go Station - 孚海國際車業站', 121.5108481, 25.0856256],
       ['Gogoro GoStation 中油永錡彭厝站', 121.4156235, 24.9717966],
       ['Unnamed', 120.7196062, 24.1252442],
       ['Unnamed', 120.6650434, 24.1493999],
       ['gogoro', 121.5042186, 25.0308252],
       ['Unnamed', 118.317326, 24.4325657],
       ['GoStation 中油大慶加油站', 121.3952173, 25.01457],
       ['Gogoro 電池交換站', 121.7436973, 25.1303539],
       ['Gogoro 電池交換站 WorldGym 信義店 Sport站', 121.7511718, 25.1292681],
       ['GOGORO 電池交換站', 121.8235874, 25.1210417],
       ['Gogoro 電池交換站 南山社區站', 121.7760971, 25.0401632],
       ['GOGORO 電池交換站 中油成功一路站', 121.7379883, 25.1268794],
       ['Gogoro 電池交換站 中油安樂站', 121.7188453, 25.1266343],
       ['Unnamed', 121.5387466, 24.9949974],
       ['台灣電力公司', 121.1432297, 24.9050546],
       ['Unnamed', 120.2520213, 22.9701788],
       ['Unnamed', 120.6871966, 24.137306],
       ['GoStation 中油永錡保安站', 121.421369, 24.9960604],
       ['Gogoro 電池交換站', 121.6022681, 25.0839877],
       ['GoStation 台北捷運輔大站(3號出口)', 121.4365166, 25.032488],
       ['GoStation 台北捷運輔大站(4號出口)', 121.4364347, 25.0331],
       ['Unnamed', 121.2381834, 25.0816019],
       ['Unnamed', 121.2373607, 25.0824714],
       ['Unnamed', 121.2384141, 25.0813467],
       ['臺北花博超級充電站', 121.5215098, 25.0687213],
       ['Unnamed', 120.600252, 24.2549704],
       ['Unnamed', 118.4302005, 24.5026469],
       ['Unnamed', 118.4140062, 24.4886406],
       ['gogoro換電站', 120.1947852, 22.9750163],
       ['gogoro換電站', 120.1871096, 22.9882937],
       ['Unnamed', 121.5491, 25.0219871],
       ['Unnamed', 121.6316255, 24.0268576],
       ['Unnamed', 120.202, 22.9811],
       ['機場捷運手機充電站/無線上網站', 121.5145122, 25.0485745],
       ['Unnamed', 121.4675471, 24.9937322],
       ['電動車太陽能充電站', 121.3003119, 24.9928795],
       ['Unnamed', 120.4566689, 23.4895305],
       ['Unnamed', 120.6082927, 22.5951699],
       ['苗栗銅鑼科學園區超級充電站', 120.7600075, 24.4621653],
       ['Gogoro 電池交換站', 120.7032363, 24.2071259],
       ['GoStation', 121.3868732, 25.0772985],
       ['Unnamed', 120.5378464, 24.2451225],
       ['Gogoro 電池交換站 新莊福營休閒廣場站', 121.4241777, 25.0238655],
       ['Gogoro 全聯台中太平店站', 120.7118802, 24.1540575],
       ['Gogoro 家樂福便利購太平環中店站', 120.7153305, 24.1493462],
       ['Unnamed', 120.6856356, 24.1410741],
       ['Gogoro 電池交換站', 120.7037912, 24.2014059],
       ['Gogoro 電池交換站', 120.7129583, 24.2586298],
       ['Gogoro 電池交換站', 120.8258506, 24.0235225],
       ['Gogoro 電池交換站', 120.7146228, 24.2391332],
       ['Gogoro 電池交換站', 120.7210392, 24.2396014],
       ['Gogoro 電池交換站', 120.708778, 24.2458344],
       ['Gogoro 電池交換站', 120.7067339, 24.2520085],
       ['Gogoro 電池交換站', 120.715095, 24.2518884],
       ['Gogoro 電池交換站', 120.721814, 24.2532352],
       ['Gogoro 電池交換站', 120.7207349, 24.2539072],
       ['Gogoro 電池交換站', 120.7318513, 24.2503843],
       ['Unnamed', 120.6864405, 24.182745],
       ['Gogoro 電池交換站', 120.7004031, 24.2116044],
       ['Gogoro 電池交換站', 120.8241057, 24.2616816],
       ['Gogoro 電池交換站', 120.9037133, 24.169174],
       ['Gogoro 電池交換站', 120.7345849, 24.2596126],
       ['手機充電站', 120.5584246, 22.6592239],
       ['Gogoro 電池交換站', 120.7013757, 24.1796568],
       ['Gogoro 電池交換站', 120.6989124, 24.1756915],
       ['Gogoro 電池交換站', 120.6948979, 24.171295],
       ['Gogoro 電池交換站', 120.6908241, 24.1708963],
       ['Gogoro 電池交換站', 120.686595, 24.1935877],
       ['Gogoro 電池交換站', 120.681615, 24.1932693],
       ['Unnamed', 120.7320362, 24.2512589],
       ['Gogoro 電池交換站', 120.7043227, 24.2317691],
       ['Gogoro 電池交換站', 120.6859083, 24.1725521],
       ['Gogoro 電池交換站', 120.6276461, 24.3505733],
       ['Gogoro 電池交換站', 120.6318517, 24.3547987],
       ['Gogoro 電池交換站', 120.62005, 24.3463338],
       ['Gogoro 電池交換站', 120.6168471, 24.3492467],
       ['Gogoro 電池交換站', 120.5887668, 24.3433023],
       ['Gogoro 電池交換站', 120.6960391, 24.3131353],
       ['Gogoro 電池交換站', 120.7238419, 24.3156965],
       ['Gogoro 電池交換站', 120.7216948, 24.3054759],
       ['Gogoro 電池交換站', 120.7239745, 24.2977534],
       ['Gogoro 電池交換站', 120.808869, 24.2482046],
       ['Gogoro 電池交換站', 120.6685612, 24.2365062],
       ['Gogoro 電池交換站', 120.6481926, 24.2292134],
       ['Gogoro 電池交換站', 120.6527901, 24.2261722],
       ['Gogoro 電池交換站', 120.648397, 24.2178542],
       ['Tesla', 120.5884364, 24.1370666],
       ['Gogoro 電池交換站', 120.7771289, 24.2745708],
       ['Gogoro 電池交換站', 120.8261728, 24.2647406],
       ['Gogoro 電池交換站', 120.6942907, 24.2157732],
       ['Gogoro 電池交換站', 120.6825528, 24.1776878],
       ['Unnamed', 120.1864242, 22.9776184],
       ['Unnamed', 120.194509, 22.9842916],
       ['gogoro電池交換站', 121.5736946, 25.0316627],
       ['Unnamed', 121.5099101, 25.0658605],
       ['Gogoro 電池交換站', 120.8297391, 24.2528393],
       ['特斯拉 嘉義水牛公園超級充電站', 120.3875937, 23.4966086],
       ['Gogoro 電池交換站', 120.7059623, 24.2204081],
       ['Gogoro 電池交換站', 120.6897245, 22.1991671],
       ['Gogoro 電池交換站', 120.5957685, 22.3827671],
       ['Gogoro 電池交換站', 120.8811502, 22.2916162],
       ['Gogoro 電池交換站', 120.8948502, 22.341632],
       ['Gogoro 電池交換站', 121.0068252, 22.6129544],
       ['Gogoro 電池交換站', 121.1379499, 22.7420968],
       ['Gogoro 電池交換站', 121.144778, 22.7552258],
       ['Gogoro 電池交換站', 121.0922716, 22.8529643],
       ['Gogoro 電池交換站', 121.2127979, 23.1208515],
       ['Gogoro 電池交換站', 121.2522139, 23.1827391],
       ['Gogoro 電池交換站', 121.3124058, 23.3336659],
       ['Gogoro 電池交換站', 121.3761381, 23.4911843],
       ['Gogoro 電池交換站', 121.4178213, 23.6534092],
       ['Gogoro 電池交換站', 121.5087426, 23.8673732],
       ['Gogoro 電池交換站', 121.5502043, 23.9535705],
       ['Gogoro 電池交換站', 121.6014038, 23.9556891],
       ['Gogoro 電池交換站', 121.5896018, 23.9641341],
       ['Gogoro 電池交換站', 121.6002922, 23.9753166],
       ['Unnamed', 120.4496373, 23.4821495],
       ['ChargePoint', 120.4440522, 23.4545087],
       ['Unnamed', 120.454186, 23.4688106],
       ['Unnamed', 121.5392067, 25.0045327],
       ['GoStation', 120.4694739, 23.477528],
       ['GoStation', 120.4435727, 23.4557261],
       ['GoStation', 120.4422656, 23.4745881],
       ['Gogoro', 121.5426019, 25.053603],
       ['BMW i 直流高速充電站', 121.4316672, 25.0319072],
       ['Tesla Supercharger', 121.4309832, 25.0343321],
       ['Unnamed', 121.5384409, 25.0040183],
       ['Gogoro 電池交換站', 120.7062765, 24.2130359],
       ['Gogoro 電池交換站', 120.7144247, 24.2482461],
       ['Gogoro 電池交換站', 120.8790733, 24.1736041],
       ['Gogoro 電池交換站', 121.3051184, 25.0143029],
       ['Unnamed', 121.4959855, 25.078967],
       ['Gogoro 電池交換站', 121.4910825, 25.07215],
       ['Gogoro 電池交換站', 121.2941035, 24.9557994],
       ['Gogoro 電池交換站', 121.2948077, 24.9610848],
       ['Gogoro換電站', 121.5940535, 25.0845401],
       ['Gogoro 電池交換站', 121.2567532, 24.9378262],
       ['Gogoro 電池交換站', 121.4516445, 25.2258639],
       ['YES!來電 電動車充電專用車位', 121.4515377, 25.22751],
       ['Gogoro 電池交換站', 121.4470085, 25.1668261],
       ['Gogoro 電池交換站', 121.300697, 24.9662097],
       ['Gogoro 電池交換站', 121.2878512, 24.910349],
       ['Gogoro 電池交換站', 120.9941765, 24.7838559],
       ['Gogoro 電池交換站', 121.2836673, 24.8984653],
       ['Gogoro 電池交換站', 121.3055724, 24.965533],
       ['Gogoro 電池交換站', 120.5690533, 24.2166834],
       ['Unnamed', 120.9921606, 24.781198],
       ['Gogoro 電池交換站', 121.2302425, 25.0275034],
       ['Unnamed', 120.2296034, 23.0104041],
       ['Gogoro 電池交換站', 120.2463379, 22.9902334],
       ['Gogoro 電池交換站', 120.2179834, 23.0129162],
       ['Gogoro 電池交換站', 120.6244596, 24.1039918],
       ['ionex換電站', 121.2945864, 24.9654933],
       ['Gogoro 電池交換站', 121.4127389, 25.0129394],
       ['Gogoro 電池交換站', 120.1908146, 22.9920582],
       ['Gogoro 電池交換站', 120.1888432, 22.9921323],
       ['Unnamed', 121.3804378, 25.0767122],
       ['EValue 三井林口', 121.3651784, 25.0711405],
       ['BEGIN 林口惠民站', 121.3569967, 25.0669552],
       ['U-Power 台南裕農站', 120.2445923, 22.9902051],
       ['Gogoro 電池交換站', 121.5530933, 25.0236791],
       ['Gogoro 電池交換站', 120.2477926, 22.8836698],
       ['Gogoro 電池交換站', 120.2478533, 22.8836236],
       ['Gogoro 電池交換站', 121.2241593, 24.9494991],
       ['Gogoro 電池交換站', 120.2165952, 22.9955985],
       ['Gogoro 電池交換站 - 全家平溪十分店站', 121.7793362, 25.0446486],
       ['Gogoro 電池交換站 - 新北市貢寮市民活動中心站', 121.907564, 25.0204941],
       ['Gogoro 電池交換站', 120.7025098, 24.1970833],
       ['Gogoro 電池交換站', 120.2237662, 23.0104024],
       ['Gogoro 電池交換站', 121.4603165, 25.0071263],
       ['Gogoro 電池交換站', 121.4767022, 25.0054687],
       ['Gogoro 電池交換站', 121.4758782, 25.0034986],
       ['Gogoro 電池交換站', 121.5038335, 25.0353103],
       ['Unnamed', 120.6968006, 24.0554737],
       ['Gogoro 電池交換站', 120.6461918, 24.1398412],
       ['Gogoro 電池交換站', 120.1923232, 23.0113899],
       ['Gogoro 電池交換站', 120.2292396, 22.9997652],
       ['Gogoro 電池交換站土城站', 121.4651156, 24.9887013],
       ['Gogoro 電池交換站', 120.2152446, 23.0045708],
       ['Unnamed', 121.3596322, 25.0450153],
       ['Gogoro 電池交換站', 120.3077186, 22.5977629],
       ['Gogoro 電池交換站', 121.521982, 25.2856274],
       ['Gogoro 電池交換站', 121.6022178, 25.0033699],
       ['Gogoro 電池交換站', 120.171494, 22.9959392],
       ['Gogoro 電池交換站', 120.1882465, 23.0388165],
       ['Unnamed', 120.9258412, 23.9729786],
       ['Gogoro 電池交換站', 120.2313326, 22.9875975],
       ['Unnamed', 121.240664, 25.081652],
       ['Tesla Supercharger', 120.9707782, 24.8195148],
       ['Unnamed', 120.5431616, 24.2667136],
       ['Unnamed', 120.5342795, 24.2695488],
       ['Unnamed', 120.5404191, 24.2660278],
       ['Unnamed', 120.5361882, 24.2693792],
       ['Unnamed', 120.53793, 24.2676123],
       ['Gogoro 電池交換站', 121.3161751, 25.007321],
       ['iONEX電池交換站', 120.294183, 22.6234395],
       ['Gogoro 電池交換站', 121.3223102, 24.9957029],
       ['便利換電站', 120.4487279, 23.47688],
       ['Gogoro 電池交換站', 121.3198435, 25.0097973],
       ['Unnamed', 121.6117678, 23.9778468],
       ['Gogoro', 120.1895221, 23.2442729],
       ['Gogoro 電池交換站', 121.3164868, 25.0162591],
       ['Gogoro 電池交換站', 121.5629831, 24.9900077],
       ['Gogoro 電池交換站', 120.2202187, 22.9841923],
       ['Gogoro 電池交換站', 120.2088941, 22.9824681],
       ['Gogoro 電池交換站', 120.2189719, 23.0072657],
       ['Unnamed', 120.2191796, 23.0075321],
       ['Gogoro 電池交換站', 120.2087793, 22.999036],
       ['Gogoro 電池交換站', 120.5209775, 23.4422173],
       ['Gogoro換電站', 121.5182913, 25.0263089],
       ['Gogoro 電池交換站', 120.1921588, 22.99312],
       ['Gogoro 電池交換站', 121.5589232, 25.0377852],
       ['Gogoro 電池交換站', 121.566582, 25.0442643],
       ['Gogoro 電池交換站', 121.546046, 25.0490232],
       ['Unnamed', 120.6969844, 22.0462156],
       ['Unnamed', 121.8448101, 24.5688698],
       ['Unnamed', 120.2694972, 22.6241255],
       ['iONEX電池交換站', 120.4368493, 23.4582543],
       ['Gogoro 電池交換站', 120.254225, 23.0247462],
       ['U-POWER 汐止大同站', 121.6831533, 25.0742641],
       ['Unnamed', 120.3150887, 22.6638605],
       ['Unnamed', 120.3131079, 22.6627616],
       ['Gogoro 電池交換站', 120.2339705, 22.9910541],
       ['Gogoro換電站', 121.5085753, 25.0307918],
       ['Gogoro換電站', 121.5207725, 25.0153507],
       ['Unnamed', 121.5362183, 24.4957314],
       ['Gogoro 電池交換站', 121.2981549, 24.9950759],
       ['Gogoro 電池交換站', 121.2578293, 25.0208225],
       ['Gogoro 電池交換站', 120.538112, 24.0809864],
       ['Gogoro 電池交換站', 120.1946775, 23.0800414],
       ['Gogoro 電池交換站', 121.54259, 24.9993709],
       ['Unnamed', 121.3932308, 25.0475345],
       ['Unnamed', 121.4097668, 24.8280282],
       ['Gogoro 電池交換站', 120.2105661, 22.9911558],
       ['Gogoro 電池交換站', 120.4952413, 22.8825522],
       ['ionex', 121.0233748, 24.8678707],
       ['Unnamed', 120.2187355, 23.0064042],
       ['Gogoro 電池交換站', 120.4760022, 23.9635156],
       ['Gogoro 電池交換站', 120.2679359, 22.6119457],
       ['U-POWER 充電站', 121.3069982, 24.969691],
       ['U-POWER', 121.5737495, 24.9980262],
       ['Unnamed', 121.2934442, 24.9982439],
       ['Gogoro 電池交換站', 120.4445508, 23.7096002],
       ['Gogoro 電池交換站', 120.2311901, 23.0083057],
       ['Gogoro 電池交換站', 120.1347125, 23.0685968],
       ['Unnamed', 121.6963989, 25.1569924],
       ['Gogoro 電池交換站', 121.5561181, 25.0849187],
       ['集賢館充電樁（快充）', 121.5473529, 23.9021918],
       ['行政大樓充電樁（快充）', 121.5425581, 23.8944327],
       ['理工三館充電樁（快充）', 121.5450979, 23.8973724],
       ['理工三館充電樁（慢充）', 121.5451209, 23.8973153],
       ['東華會館充電樁（快充）', 121.5480916, 23.8954317],
       ['東華會館充電樁（慢充）', 121.5481261, 23.8953758],
       ['多容館充電樁（慢充）', 121.5344026, 23.8948194],
       ['多容館充電樁（快充）', 121.5343769, 23.8949086],
       ['Unnamed', 120.2180147, 22.996648],
       ['Gogoro 電池交換站', 121.6961509, 25.1558856],
       ['Unnamed', 121.4109587, 25.0211694]], dtype=object)

In [40]:
taiwan_charger_cleaned_2 = pd.DataFrame(
    taiwan_charger_cleaned_2, columns=taiwan_charger_cleaned.columns
)

In [43]:
taiwan_charger_cleaned_2['name'].value_counts()

name
Gogoro 電池交換站    138
Unnamed          62
GoStation         4
Gogoro換電站         4
gogoro換電站         2
               ...
理工三館充電樁（慢充）       1
東華會館充電樁（快充）       1
東華會館充電樁（慢充）       1
多容館充電樁（慢充）        1
多容館充電樁（快充）        1
Name: count, Length: 73, dtype: int64

In [44]:
taiwan_charger_cleaned_2.to_csv('data/taiwan_ev_station_mock.csv', index=False)