In [7]:
import pandas as pd

pd.set_option('display.max_columns', None)
data = pd.read_csv("data/ChargePointData2011-2020-ManullyPreCleaned3.csv")
data

C:\Users\mcu\AppData\Local\Temp\ipykernel_15176\3440117333.py:4: DtypeWarning: Columns (0: User ID, 1: County, 2: Model Number) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("data/ChargePointData2011-2020-ManullyPreCleaned3.csv")

,Station Name,MAC Address,Org Name,Start Date,Start Time Zone,End Date,End Time Zone,Transaction Date (Pacific Time),Total Duration (hh:mm:ss),Charging Time (hh:mm:ss),Energy (kWh),GHG Savings (kg),Gasoline Savings (gallons),Port Type,Port Number,Plug Type,EVSE ID,Address 1,City,State/Province,Postal Code,Country,Latitude,Longitude,Currency,Fee,Ended By,Plug In Event Id,Driver Postal Code,User ID,County,System S/N,Model Number
0,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/29/2011 20:17,PDT,7/29/2011 23:20,PDT,7/29/2011 23:20,03:03:32,01:54:03,6.249457,2.625,0.784,Level 2,2,J1772,NaN,250 Hamilton Ave,Palo Alto,California,94301,United States,37.444572,-122.160309,USD,0.00,Plug Out at Vehicle,3,95124.0,3284.0,NaN,NaN,NaN
1,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 0:00,PDT,7/30/2011 0:02,PDT,7/30/2011 0:02,00:02:06,00:01:54,0.106588,0.045,0.013,Level 2,2,J1772,NaN,250 Hamilton Ave,Palo Alto,California,94301,United States,37.444572,-122.160309,USD,0.00,Customer,4,94301.0,4169.0,NaN,NaN,NaN
2,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 8:16,PDT,7/30/2011 12:34,PDT,7/30/2011 12:34,04:17:32,04:17:28,14.951777,6.280,1.876,Level 2,2,J1772,NaN,250 Hamilton Ave,Palo Alto,California,94301,United States,37.444572,-122.160309,USD,0.00,Plug Out at Vehicle,5,94301.0,4169.0,NaN,NaN,NaN
3,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 14:51,PDT,7/30/2011 16:55,PDT,7/30/2011 16:55,02:03:24,02:02:58,7.159643,3.007,0.899,Level 2,2,J1772,NaN,250 Hamilton Ave,Palo Alto,California,94301,United States,37.444572,-122.160309,USD,0.00,Customer,6,94302.0,2545.0,NaN,NaN,NaN
4,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 18:51,PDT,7/30/2011 20:03,PDT,7/30/2011 20:03,01:11:24,00:43:54,1.957765,0.822,0.246,Level 2,2,J1772,NaN,250 Hamilton Ave,Palo Alto,California,94301,United States,37.444572,-122.160309,USD,0.00,Plug Out at Vehicle,7,94043.0,3765.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259410,PALO ALTO CA / TED THOMPSON #3,0024:B100:0002:9F81,City of Palo Alto,12/31/2020 16:39,PST,12/31/2020 17:14,PST,12/31/2020 17:16,00:35:44,00:35:18,1.841000,0.773,0.231,Level 2,2,J1772,344261.0,275 Cambridge Ave,Palo Alto,California,94306,United States,37.428623,-122.144043,USD,0.42,Plug Out at Vehicle,2369,94301.0,2024201,NaN,1.750000e+11,CT4020-HD-GW
259411,PALO ALTO CA / WEBSTER #1,0024:B100:0002:4233,City of Palo Alto,12/31/2020 16:48,PST,12/31/2020 20:31,PST,12/31/2020 20:32,03:43:01,02:14:04,12.744000,5.352,1.599,Level 2,2,J1772,104427.0,520 Webster St,Palo Alto,California,94301,United States,37.448284,-122.158272,USD,4.69,Plug Out at Vehicle,7255,94541.0,242661,Santa Clara County,1.340000e+11,CT4020-HD-GW
259412,PALO ALTO CA / MPL #4,0024:B100:0003:CD37,City of Palo Alto,12/31/2020 17:28,PST,1/1/2021 10:56,PST,1/1/2021 10:57,17:28:14,05:08:12,29.665000,12.459,3.723,Level 2,1,J1772,2884001.0,3700 Middlefield Rd,Palo Alto,California,94303,United States,37.422104,-122.113510,USD,6.82,Plug Out at Vehicle,455,94306.0,449995,Santa Clara County,2.000000e+11,CT4010-HD-GW
259413,PALO ALTO CA / WEBSTER #1,0024:B100:0002:4233,City of Palo Alto,12/31/2020 17:49,PST,12/31/2020 21:55,PST,12/31/2020 21:56,04:05:34,03:53:42,11.976000,5.030,1.503,Level 2,1,J1772,104427.0,520 Webster St,Palo Alto,California,94301,United States,37.448284,-122.158272,USD,2.75,Plug Out at Vehicle,7256,94552.0,804075,Santa Clara County,1.340000e+11,CT4020-HD-GW
259414,PALO ALTO CA / CAMBRIDGE #4,0024:B100:0003:3A0A,City of Palo Alto,12/31/2020 18:19,PST,12/31/2020 19:01,PST,12/31/2020 19:02,00:42:07,00:41:44,1.571000,0.660,0.197,Level 2,1,J1772,337571.0,475 Cambridge Ave,Palo Alto,California,94306,United States,37.426178,-122.146034,USD,0.36,Plug Out at Vehicle,2302,94305.0,2022651,Santa Clara County,1.850000e+11,CT4020-HD-GW

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 259415 entries, 0 to 259414
Data columns (total 33 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Station Name                     259415 non-null  str
 1   MAC Address                      259415 non-null  str
 2   Org Name                         259415 non-null  str
 3   Start Date                       259415 non-null  str
 4   Start Time Zone                  259415 non-null  str
 5   End Date                         259415 non-null  str
 6   End Time Zone                    259415 non-null  str
 7   Transaction Date (Pacific Time)  259207 non-null  str
 8   Total Duration (hh:mm:ss)        259415 non-null  str
 9   Charging Time (hh:mm:ss)         259415 non-null  str
 10  Energy (kWh)                     259415 non-null  float64
 11  GHG Savings (kg)                 259415 non-null  float64
 12  Gasoline Savings (gallons)       259415 non-null  float64
 13  Port Type                        259406 non-null  str
 14  Port Number                      259415 non-null  int64
 15  Plug Type                        259415 non-null  str
 16  EVSE ID                          180467 non-null  float64
 17  Address 1                        259415 non-null  str
 18  City                             259415 non-null  str
 19  State/Province                   259415 non-null  str
 20  Postal Code                      259415 non-null  int64
 21  Country                          259415 non-null  str
 22  Latitude                         259415 non-null  float64
 23  Longitude                        259415 non-null  float64
 24  Currency                         257627 non-null  str
 25  Fee                              259415 non-null  float64
 26  Ended By                         259167 non-null  str
 27  Plug In Event Id                 259415 non-null  int64
 28  Driver Postal Code               251013 non-null  float64
 29  User ID                          251738 non-null  object
 30  County                           174750 non-null  str
 31  System S/N                       180467 non-null  float64
 32  Model Number                     180467 non-null  str
dtypes: float64(9), int64(3), object(1), str(20)
memory usage: 65.3+ MB

In [5]:
data['Energy (kWh)']

0          6.249457
1          0.106588
2         14.951777
3          7.159643
4          1.957765
            ...
259410     1.841000
259411    12.744000
259412    29.665000
259413    11.976000
259414     1.571000
Name: Energy (kWh), Length: 259415, dtype: float64

In [6]:
data.head(5)

,Station Name,MAC Address,Org Name,Start Date,Start Time Zone,End Date,End Time Zone,Transaction Date (Pacific Time),Total Duration (hh:mm:ss),Charging Time (hh:mm:ss),...,Longitude,Currency,Fee,Ended By,Plug In Event Id,Driver Postal Code,User ID,County,System S/N,Model Number
0,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/29/2011 20:17,PDT,7/29/2011 23:20,PDT,7/29/2011 23:20,03:03:32,01:54:03,...,-122.160309,USD,0.0,Plug Out at Vehicle,3,95124.0,3284.0,NaN,NaN,NaN
1,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 0:00,PDT,7/30/2011 0:02,PDT,7/30/2011 0:02,00:02:06,00:01:54,...,-122.160309,USD,0.0,Customer,4,94301.0,4169.0,NaN,NaN,NaN
2,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 8:16,PDT,7/30/2011 12:34,PDT,7/30/2011 12:34,04:17:32,04:17:28,...,-122.160309,USD,0.0,Plug Out at Vehicle,5,94301.0,4169.0,NaN,NaN,NaN
3,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 14:51,PDT,7/30/2011 16:55,PDT,7/30/2011 16:55,02:03:24,02:02:58,...,-122.160309,USD,0.0,Customer,6,94302.0,2545.0,NaN,NaN,NaN
4,PALO ALTO CA / HAMILTON #1,000D:6F00:015A:9D76,City of Palo Alto,7/30/2011 18:51,PDT,7/30/2011 20:03,PDT,7/30/2011 20:03,01:11:24,00:43:54,...,-122.160309,USD,0.0,Plug Out at Vehicle,7,94043.0,3765.0,NaN,NaN,NaN

In [ ]:
other_data = pd.read_csv("Algorithm/ev_stations_2025.csv")
other_data